const ProblemTwo = {
  title: 'Even Fibonacci Numbers',
  goal: 4000000,
  solution: (goal) => {
    let fibonacci = [1,2];
    let sum = 0;
    while (sum <= goal) {
      let previousTwoNumbers = fibonacci.slice(-2);
      sum = previousTwoNumbers[0] + previousTwoNumbers[1];
      fibonacci.push(sum);
    }
    let evenSums = fibonacci.filter(sum => sum % 2 === 0);
    return evenSums.reduce((a, b) => a + b, 0);
  },
  description: `
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    `,
  href: 'https://projecteuler.net/problem=2'
}

export default ProblemTwo;
